{{- if .Values.components.crossplane.enabled }}
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xawsbuckets.platform.io
spec:
  group: platform.io
  names:
    kind: XAWSBucket
    plural: xawsbuckets
  claimNames:
    kind: AWSBucket
    plural: awsbuckets
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    bucketName:
                      type: string
                    region:
                      type: string
                    isEncrypted:
                      type: boolean
                      default: true
                  required:
                    - bucketName
                    - region
                    - isEncrypted
{{- end }}