replicaCount: 1

image:
  repository: "ghcr.io/ok-karthik/platform-engineering-idp-gitops-reference-architecture/demo-tenant/demo-python-app"
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  instrumentation.opentelemetry.io/inject-python: "demo-python-app-autoinstrumentation"

podLabels: 
  team: "demo-tenant"

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8080

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: "demo-python-app.demo-tenant.localhost"
      paths:
        - path: /
          pathType: Prefix