---
# Source: app-a/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-a
  labels:
    helm.sh/chart: app-a-0.1.0
    app.kubernetes.io/name: app-a
    app.kubernetes.io/instance: app-a
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    team: team-a
automountServiceAccountToken:
---
# Source: app-a/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-a
  labels:
    helm.sh/chart: app-a-0.1.0
    app.kubernetes.io/name: app-a
    app.kubernetes.io/instance: app-a
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    team: team-a
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: app-a
    app.kubernetes.io/instance: app-a
---
# Source: app-a/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
  labels:
    helm.sh/chart: app-a-0.1.0
    app.kubernetes.io/name: app-a
    app.kubernetes.io/instance: app-a
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    team: team-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app-a
      app.kubernetes.io/instance: app-a
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: app-a-autoinstrumentation
      labels:
        helm.sh/chart: app-a-0.1.0
        app.kubernetes.io/name: app-a
        app.kubernetes.io/instance: app-a
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/managed-by: Helm
        team: team-a
    spec:
      serviceAccountName: app-a
      containers:
        - name: app-a
          image: "ghcr.io/ok-karthik/platform-engineering-idp-gitops-reference-architecture/team-a/app-a:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
# Source: app-a/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-a
  labels:
    helm.sh/chart: app-a-0.1.0
    app.kubernetes.io/name: app-a
    app.kubernetes.io/instance: app-a
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    team: team-a
spec:
  ingressClassName: traefik
  rules:
    - host: "app-a.team-a.localhost"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-a
                port:
                  number: 8080
---
# Source: app-a/templates/instrumentation.yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: app-a-autoinstrumentation
  labels:
    helm.sh/chart: app-a-0.1.0
    app.kubernetes.io/name: app-a
    app.kubernetes.io/instance: app-a
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    team: team-a
spec:
  exporter:
    # Point traces to the centralized Tempo service running in the monitoring namespace
    endpoint: http://tempo.monitoring.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_always_on
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
    env:
      - name: OTEL_PYTHON_DISABLED_INSTRUMENTATIONS
        value: "system_metrics"
      - name: OTEL_LOGS_EXPORTER
        value: "none"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
