{{- if .Values.components.sealedSecretDemo.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-api-key
  namespace: default
spec:
  encryptedData:
    api-token: AgArx6nI32W2F/HFp9nvPo0TVpdMkQPQ2KzL6fmdwp3EFfSt/k/h4tbDZrapV1hFI4LUpvOhtwIMKO/s0vyKY42eoOXdHzGG5Q1PvvdEf81lNFg+CUxRkf//hKVhAaMNBaGvFVq8PHgMlslMSfmArRBB1i+85zW2NFortMuZsEfyHWKLv2X0eXL/geaUFJpprwQCbXsWR4H8Kv84gh4pBvFA/6lFpT9tR9qBiBOHc6oMA0SFVyoOakJdPtukQVEQjjdcwxGUv3yETTEMp57tSljuTFVLCmtLVv4qewJN5kVPKpKymaI4WkV/k4rs9WHSk+jjWheiuu+ouf8ScsYd3UtuSccnzcowxB59KFck00jTNtiWpKWJKRbu34dLdfkiTJD7OTZfjKKInFA4MnfAgmZAX2VKMy8kKKBCrEZDX6ATadRjKLER5RyLjRD1d+D5HNcGxqmZ+pdC88C97GRazRI86AAV/xaHXBGvdCAUWkwCGsXlchtIIG53uKXZDHEFhzAI8nd1Qb9GFb6uECwow6xY2GR0OmVce7p77NanGZRGS32VuKxcxns07sxL0x4mBz1AExJ/HSb+KamFlHpsZTpfvpRGK3zqdant1Dz9BnnTlzfeYfrnECSPmB/TIZViJxJBlL1+AXOVVX5ZC19yLbRE1J8+GSXs99eXL4fLimi5AY17hP0OVtN2hfuhcO22zFmSqWD0aOskc+MjgwCi6/IMLmny2dpAdifC
  template:
    metadata:
      name: my-api-key
      namespace: default
{{- end }}
