apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
    targetRevision: '0.65.0'
    chart: opentelemetry-operator
    helm:
      values: |
        admissionWebhooks:
          certManager:
            enabled: true
        manager:
          collectorImage:
            repository: otel/opentelemetry-collector-k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: opentelemetry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: 'https://github.com/ok-karthik/platform-engineering-idp-gitops-reference-architecture.git'
    targetRevision: HEAD
    path: 4-platform-infrastructure/otel-setup
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
