apiVersion: v1
kind: Service
metadata:
  name: {{ app_name}}
  labels:
    app: {{ app_name}}
spec:
  type: ClusterIp
  ports:
    - port: {{ app_port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ app_name}}
