name: CD Pipeline - Render & Push my-python-app

on:
  push:
    branches:
      - main
    paths:
      - 'apps/my-python-app/templated-manifests/**'

jobs:
  render:
    name: Render manifests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Render the manifests
        run: |
          cd apps/my-python-app
          helm template my-python-app templated-manifests | awk -v out="rendered-manifests" -F": " '$0~/^# Source: /{file=$2; sub(/^[^\/]+\/templates\//, "", file); file=out"/"file; dir=file; sub(/\/[^\/]+$/, "", dir); system("mkdir -p \"" dir "\""); print > file} $0!~/^#/ && $0!="---"{print >> file}'

      # Implement blue-green deployment later https://github.com/argoproj/argocd-example-apps/tree/master/blue-green