apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/ok-karthik/platform-engineering-idp-gitops-reference-architecture.git'
        revision: HEAD
        directories:
          - path: 2-tenant-workloads/*/*-gitops-repo/apps/*
  template:
    metadata:
      name: '{{path[1]}}-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/ok-karthik/platform-engineering-idp-gitops-reference-architecture.git'
        targetRevision: HEAD
        path: '{{path}}/rendered-manifests'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path[1]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
