{{- if .Values.components.certManager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  project: {{ .Values.spec.project }}
  source:
    repoURL: 'https://charts.jetstack.io/'
    targetRevision: 'v1.20.1'
    chart: cert-manager
    helm:
      parameters:
        - name: "crds.enabled"
          value: "true"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
