{{- if .Values.components.traefik.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  project: {{ .Values.spec.project }}
  source:
    repoURL: 'https://traefik.github.io/charts'
    targetRevision: '26.0.0'
    chart: traefik
    helm:
      parameters:
        - name: "providers.kubernetesIngress.publishedService.enabled"
          value: "true"
        - name: "providers.kubernetesCRD.allowCrossNamespace"
          value: "true"
        - name: "ports.traefik.expose"
          value: "true"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
