spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

components:
  argoRollouts:
    enabled: true
  certManager:
    enabled: true
  crossplane:
    enabled: false
  kyverno:
    enabled: false
  sealedSecrets:
    enabled: true
  sealedSecretDemo:
    enabled: false
  traefik:
    enabled: true
  argocdIngress:
    enabled: true
  loki:
    enabled: true
  opentelemetry:
    enabled: true
  prometheus:
    enabled: true
  tempo:
    enabled: true