name: CD Pipeline - Render & Push app-a

on:
  push:
    branches:
      - main
    paths:
      - 'helm-charts/app-a/**'

jobs:
  render:
    name: Render manifests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Render the manifests
        run: |
          # Convert GitHub repository path to lowercase for Docker registry compatibility
          IMAGE_REPO=$(echo "ghcr.io/${{ github.repository }}/team-b/app-a" | tr '[:upper:]' '[:lower:]')

          # Render Helm chart overriding the image repository
          helm template app-a helm-charts/app-a \
            --set image.repository="$IMAGE_REPO" \
            --output-dir rendered-manifests

      # Implement blue-green deployment later https://github.com/argoproj/argocd-example-apps/tree/master/blue-green