{{- if .Values.components.tenantApps.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-apps
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  generators:
    - git:
        repoURL: 'https://github.com/ok-karthik/platform-engineering-idp-gitops-reference-architecture.git'
        revision: HEAD
        directories:
          - path: generated-apps/*/*-gitops-repo/apps/*
  template:
    metadata:
      name: '{{`{{path[1]}}`}}-{{`{{path.basename}}`}}'
    spec:
      project: {{ .Values.spec.project }}
      source:
        repoURL: 'https://github.com/ok-karthik/platform-engineering-idp-gitops-reference-architecture.git'
        targetRevision: HEAD
        path: '{{`{{path}}`}}/rendered-manifests'
      destination:
        server: {{ .Values.spec.destination.server }}
        namespace: '{{`{{path.basename}}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
{{- end }}
