apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://traefik.github.io/charts'
    targetRevision: '26.0.0'
    chart: traefik
    helm:
      parameters:
        - name: "providers.kubernetesIngress.publishedService.enabled"
          value: "true"
        - name: "providers.kubernetesCRD.allowCrossNamespace"
          value: "true"
        - name: "ports.traefik.expose"
          value: "true"
        - name: "providers.kubernetesGateway.enabled"
          value: "true"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: 'https://github.com/ok-karthik/platform-engineering-idp-gitops-reference-architecture.git'
    targetRevision: HEAD
    path: 4-platform-infrastructure/traefik-setup
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
