# Source: demo-python-app/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-python-app
  labels:
    helm.sh/chart: demo-python-app-0.1.0
    app.kubernetes.io/name: demo-python-app
    app.kubernetes.io/instance: demo-python-app
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken:
