{{- if .Values.components.loki.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: {{ .Values.spec.destination.namespace }}
spec:
  project: {{ .Values.spec.project }}
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: '6.6.0'
    chart: loki
    helm:
      parameters:
        - name: "deploymentMode"
          value: "SingleBinary"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
